# Generated by Django 5.2.8 on 2025-12-03 19:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='qualifiers',
        ),
        migrations.CreateModel(
            name='RecipeIngredientQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_qualifiers', to='recipes.recipeingredient')),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.qualifier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
