# Generated by Django 6.0 on 2026-01-12 20:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_remove_recipeingredient_qualifiers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='recipeingredientqualifier',
            name='qualifier',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='page',
        ),
        migrations.RemoveField(
            model_name='recipeingredientqualifier',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
        migrations.DeleteModel(
            name='Qualifier',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeIngredientQualifier',
        ),
    ]
