# Generated by Django 6.0 on 2026-01-12 21:00

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0005_remove_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepage',
            name='directions',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='font',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='processed_description',
            field=wagtail.fields.RichTextField(
                blank=True, help_text='Versão final após IA.', verbose_name='Descrição processada'
            ),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Rascunho'),
                    ('pending_review', 'Pendente Review'),
                    ('final_review', 'Review Final'),
                    ('published', 'Publicada'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='recipepage',
            name='description',
            field=wagtail.fields.RichTextField(
                help_text='Escreva descrição, ingredientes, preparo e fonte. Será processado automaticamente.',
                verbose_name='Descrição completa (crua)',
            ),
        ),
    ]
