# Generated by Django 6.0 on 2026-01-14 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_remove_recipepage_directions_remove_recipepage_font_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepage',
            old_name='description',
            new_name='input_description',
        ),
    ]
