# Generated by Django 6.0 on 2026-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_rename_description_recipepage_input_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending IA'), ('in_review', 'In Review'), ('published', 'Published')], default='draft', editable=False, max_length=20),
        ),
    ]
