# Generated by Django 6.0.3 on 2026-03-10 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipepage_status'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessingTask',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.task')),
            ],
            options={
                'verbose_name': 'AI Processing Task',
                'verbose_name_plural': 'AI Processing Tasks',
            },
            bases=('wagtailcore.task',),
        ),
    ]
