# Generated by Django 6.0.3 on 2026-04-29 19:45

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0009_aiprocessingtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Nome')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                (
                    'abbr',
                    models.CharField(help_text='Ex: g, ml, xíc., colher', max_length=10, verbose_name='Abreviação'),
                ),
            ],
            options={
                'verbose_name': 'Métrica',
                'verbose_name_plural': 'Métricas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'name',
                    models.CharField(
                        help_text='Ex: picado, ralado, em cubos, opcional', max_length=64, verbose_name='Nome'
                    ),
                ),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='input_description',
        ),
        migrations.RemoveField(
            model_name='recipepage',
            name='processed_description',
        ),
        migrations.AddField(
            model_name='recipepage',
            name='description',
            field=models.TextField(blank=True, help_text='Breve descrição da receita.', verbose_name='descrição'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='directions',
            field=wagtail.fields.RichTextField(blank=True, help_text='Passos para o preparo.', verbose_name='preparo'),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='font',
            field=models.CharField(
                blank=True, help_text='Livro de receita, link do youtube e etc.', max_length=200, verbose_name='fonte'
            ),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='raw_ai_response',
            field=models.JSONField(
                blank=True,
                help_text='JSON retornado pela IA para aprendizado.',
                null=True,
                verbose_name='Resposta bruta da IA',
            ),
        ),
        migrations.AddField(
            model_name='recipepage',
            name='raw_input',
            field=wagtail.fields.RichTextField(
                blank=True, help_text='Texto cru da receita para processamento por IA.', verbose_name='Entrada bruta'
            ),
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Quantidade')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.ingredient')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.metric')),
                (
                    'page',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipepage'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredientQualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'ingredient',
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ingredient_qualifiers',
                        to='recipes.recipeingredient',
                    ),
                ),
                ('qualifier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipes.qualifier')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
